version: "3.9"

services:
  #  postgrespatronihaproxyefcoredemo:
  #    image: postgrespatronihaproxyefcoredemo
  #    build:
  #      context: .
  #      dockerfile: PostgresPatroniHaproxyEfcoreDemo/Dockerfile

  # etcd for Patroni leader election
  etcd:
    image: quay.io/coreos/etcd:v3.5.17
    container_name: etcd1
    environment:
      ETCD_NAME: etcd1
      DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: postgres-ha-cluster
    networks: [ demo ]
    volumes:
      - pgsql_patroni_etcd_efcore_demo_etcd_data:/etcd-data
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  # Patroni node 1 (using Zalando Spilo)
  patroni1:
    image: ghcr.io/zalando/spilo-17:4.0-p3
    container_name: patroni1
    environment:
      SCOPE: postgres-ha # cluster name, multiple Spilos belonging to the same cluster must have identical scope.
      ETCD3_HOSTS: '"etcd:2379"' # list of Etcd hosts in format '"host1:port1","host2:port2",...,"hostN:portN"'.
      SPILO_PROVIDER: 'local' # https://github.com/zalando/spilo/blob/84ab3860ddbaca5b18dfe8e2b6c124c9d5273ca9/postgres-appliance/scripts/configure_spilo.py#L398
    networks: [ demo ]
    depends_on: [ etcd ]
    volumes:
      - pgsql_patroni_etcd_efcore_demo_patroni1_data:/home/postgres/pgdata

  # Patroni node 2 (using Zalando Spilo)
  patroni2:
    image: ghcr.io/zalando/spilo-17:4.0-p3
    container_name: patroni2
    environment:
      SCOPE: postgres-ha
      ETCD3_HOSTS: '"etcd:2379"'
      SPILO_PROVIDER: 'local'
    networks: [ demo ]
    depends_on: [ etcd ]
    volumes:
      - pgsql_patroni_etcd_efcore_demo_patroni2_data:/home/postgres/pgdata

  # Patroni node 3 (using Zalando Spilo)
  patroni3:
    image: ghcr.io/zalando/spilo-17:4.0-p3
    container_name: patroni3
    environment:
      SCOPE: postgres-ha
      ETCD3_HOSTS: '"etcd:2379"'
      SPILO_PROVIDER: 'local'
    networks: [ demo ]
    depends_on: [ etcd ]
    volumes:
      - pgsql_patroni_etcd_efcore_demo_patroni3_data:/home/postgres/pgdata

networks:
  demo:

volumes:
  pgsql_patroni_etcd_efcore_demo_etcd_data:
    driver: local
  pgsql_patroni_etcd_efcore_demo_patroni1_data:
    driver: local
  pgsql_patroni_etcd_efcore_demo_patroni2_data:
    driver: local
  pgsql_patroni_etcd_efcore_demo_patroni3_data:
    driver: local