version: "3.9"

services:
  #  postgrespatronihaproxyefcoredemo:
  #    image: postgrespatronihaproxyefcoredemo
  #    build:
  #      context: .
  #      dockerfile: PostgresPatroniHaproxyEfcoreDemo/Dockerfile

  # etcd for Patroni leader election
  etcd:
    image: quay.io/coreos/etcd:v3.5.17
    container_name: pgsql_patroni_etcd_efcore_demo_etcd
    environment:
      ETCD_NAME: etcd1
      DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd:2380
      ETCD_INITIAL_CLUSTER: etcd1=http://etcd:2380
      ETCD_INITIAL_CLUSTER_STATE: new
    volumes:
      - pgsql_patroni_etcd_efcore_demo_etcd_data:/etcd-data
    healthcheck:
      test: [ "CMD", "etcdctl", "endpoint", "health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  pgsql_patroni_etcd_efcore_demo_etcd_data:
    driver: local